api :
    type: rest
    resource: "@RecipeBundle/Controller/ApiController.php"
    prefix:   api/

recipe_homepage:
    resource: "@RecipeBundle/Controller/"
    type:     annotation
    prefix:   /

new_recipe:
    resource: "@RecipeBundle/Controller/"
    type:     annotation
    prefix:   /