api :
    type: rest
    resource: "@RecipeBundle/Controller/ApiController.php"
    prefix:   api/

new_recipe:
    resource: "@RecipeBundle/Controller/AddRecipeController.php"
    type:     annotation
    prefix:   /

recipe_homepage:
    resource: "@RecipeBundle/Controller/HomePageController.php"
    type:     annotation
    prefix:   /
