services:
    recipe.rating:
        class: NfqAkademija\RecipeBundle\Services\RatingService
        calls:
            - [setRequest, [@request_stack]]
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]

    recipe.service:
        class: NfqAkademija\RecipeBundle\Services\RecipeService
        arguments:
            em: "@doctrine"
