services:
    recipe.rating:
        class: NfqAkademija\RecipeBundle\Services\RatingService
        arguments:
            em: "@doctrine"

    recipe.service:
        class: NfqAkademija\RecipeBundle\Services\RecipeService
        arguments:
            em: "@doctrine"
